[workspace]
resolver = "2"

members = [
  "maelstrom-rs",
  "c1-echo",
]

[workspace.dependencies]
tokio = { version = "1.32.0", features = [ "io-util", "io-std" ] }
serde = { version = "1.0.188", features = ["derive" ] }
serde_json = "1.0.107"